export const SAVE_USER = 'SAVE_USER';
export const REMOVE_FROM_ACTION_QUEUE = 'REMOVE_FROM_ACTION_QUEUE';
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
export const ADD_TO_ACTION_QUEUE = 'ADD_TO_ACTION_QUEUE';
export const INCREMENT_USER_INDEX = 'INCREMENT_USER_INDEX';
export const USER_REQUEST = 'USER_REQUEST';

